<?php
  include 'enablecache.php';
?>
{
  "beers": [
  {
    "id": 1000,
    "brewerId": 22,
    "name": "Salty Dog",
    "abv": 5,
    "styleId": 27,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 2,
    "sour": 3,
    "oakAged": false,
    "tags": "spices",
    "ratebeerId": 384612,
    "untappdId": -1
  },
  {
    "id": 1001,
    "brewerId": 22,
    "name": "Amphiprion",
    "abv": 6,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 2,
    "sour": 5,
    "oakAged": false,
    "tags": "sea buckthorn",
    "ratebeerId": 436717,
    "untappdId": -1
  },
  {
    "id": 1002,
    "brewerId": 22,
    "name": "Коммендантский Час (w/ Zagovor)",
    "abv": 11,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 4,
    "bitter": 1,
    "sour": 1,
    "oakAged": false,
    "tags": "chilli,bourbon,coffee,anise",
    "ratebeerId": 442447,
    "untappdId": -1
  },
  {
    "id": 1003,
    "brewerId": 22,
    "name": "Ghost Town (Brandy B.A. w/ Brettanomyces)",
    "abv": 10.5,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 4,
    "bitter": 1,
    "sour": 1,
    "oakAged": true,
    "tags": "oats,brett,brandy",
    "ratebeerId": 330104,
    "untappdId": -1
  },
  {
    "id": 1004,
    "brewerId": 22,
    "name": "Ленинградец (Leningradets)",
    "abv": 13.2,
    "styleId": 0,
    "serving": 0,
    "colour": 3,
    "body": 5,
    "sweet": 5,
    "bitter": 1,
    "sour": 1,
    "oakAged": false,
    "tags": "oat wine",
    "ratebeerId": 417902,
    "untappdId": -1
  },
  {
    "id": 1005,
    "brewerId": 22,
    "name": "Red Maniac",
    "abv": 6.8,
    "styleId": 2,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "chilli",
    "ratebeerId": 330102,
    "untappdId": -1
  },
  {
    "id": 1006,
    "brewerId": 22,
    "name": "(Festival Beer)",
    "abv": 8,
    "styleId": 29,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1007,
    "brewerId": 22,
    "name": "Морс Атакует",
    "abv": 5.6,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1008,
    "brewerId": 22,
    "name": "Twinberry",
    "abv": 4.5,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 2,
    "sweet": 3,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "red current,black current",
    "ratebeerId": 402169,
    "untappdId": -1
  },
  {
    "id": 1009,
    "brewerId": 8,
    "name": "Mad Tom Session IPA",
    "abv": 4,
    "styleId": 28,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1010,
    "brewerId": 8,
    "name": "Ich Bin Ein Berliner Framboos",
    "abv": 4,
    "styleId": 11,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": false,
    "tags": "raspberry",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1011,
    "brewerId": 8,
    "name": "Potpils",
    "abv": 5.5,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1012,
    "brewerId": 8,
    "name": "Wild West Kriek Framboos",
    "abv": 6,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "raspberry",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1013,
    "brewerId": 8,
    "name": "Wild West Blackthorn Edition 2015",
    "abv": 6,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "blackthorn,bordeaux",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1014,
    "brewerId": 8,
    "name": "Wild West Grape Edition 2015",
    "abv": 6,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "grapes,red wine",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1015,
    "brewerId": 8,
    "name": "Cuvée Sofie",
    "abv": 8,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 4,
    "sweet": 3,
    "bitter": 1,
    "sour": 3,
    "oakAged": true,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1016,
    "brewerId": 8,
    "name": "Cuvée Sofie Dryhopped",
    "abv": 8,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 4,
    "sweet": 2,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1017,
    "brewerId": 8,
    "name": "Kriek van Mortagne",
    "abv": 8,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "sour cherry, pomerol",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1018,
    "brewerId": 8,
    "name": "Mano Negra",
    "abv": 10,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1019,
    "brewerId": 8,
    "name": "Mano Negra Cognac Barrel Aged",
    "abv": 10,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 4,
    "bitter": 3,
    "sour": 2,
    "oakAged": true,
    "tags": "cognac",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1020,
    "brewerId": 8,
    "name": "Cuvée d'Erpigny Pineau de Charentes Barrel Aged",
    "abv": 12.2,
    "styleId": 0,
    "serving": 0,
    "colour": 1,
    "body": 4,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "dessert wine",
    "ratebeerId": 436021,
    "untappdId": -1
  },
  {
    "id": 1021,
    "brewerId": 8,
    "name": "Cuvée d'Erpigny Sauternes Barrel Aged",
    "abv": 12.2,
    "styleId": 0,
    "serving": 0,
    "colour": 1,
    "body": 4,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "dessert wine",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1022,
    "brewerId": 8,
    "name": "Cuvée de Mortagne Piment d'Espelette",
    "abv": 12.8,
    "styleId": 14,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "chilli",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1023,
    "brewerId": 8,
    "name": "Cuvée de Mortagne Banuyls Barrel Aged",
    "abv": 12.8,
    "styleId": 14,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 4,
    "bitter": 2,
    "sour": 2,
    "oakAged": true,
    "tags": "dessert wine",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1024,
    "brewerId": 8,
    "name": "Alvinne & Friends #4 Insight Brewing Smokin Peaches",
    "abv": 11,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 4,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "smoked fruit",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1025,
    "brewerId": 23,
    "name": "Kramah",
    "abv": 6.5,
    "styleId": 2,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1026,
    "brewerId": 23,
    "name": "Deetz",
    "abv": 4.8,
    "styleId": 6,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1027,
    "brewerId": 23,
    "name": "Ond",
    "abv": 6.3,
    "styleId": 11,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "smoked",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1028,
    "brewerId": 23,
    "name": "Rudeen",
    "abv": 7.4,
    "styleId": 8,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1029,
    "brewerId": 23,
    "name": "Baja",
    "abv": 5.8,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "oatmeal",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1030,
    "brewerId": 23,
    "name": "Who Cares Editions Orange Unicorn",
    "abv": 6.3,
    "styleId": 17,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 3,
    "bitter": 3,
    "sour": 3,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1031,
    "brewerId": 23,
    "name": "Hagger",
    "abv": 12.3,
    "styleId": 0,
    "serving": 2,
    "colour": 4,
    "body": 4,
    "sweet": 4,
    "bitter": 1,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1032,
    "brewerId": 23,
    "name": "Kellerbier",
    "abv": 6,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1033,
    "brewerId": 24,
    "name": "ReAle Extra",
    "abv": 6.4,
    "styleId": 7,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 1,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1034,
    "brewerId": 24,
    "name": "Maledetta",
    "abv": 6.2,
    "styleId": 10,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1035,
    "brewerId": 24,
    "name": "Keto Reporter",
    "abv": 5.2,
    "styleId": 11,
    "serving": 0,
    "colour": 5,
    "body": 2,
    "sweet": 1,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "tobacco",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1036,
    "brewerId": 24,
    "name": "Duchessa",
    "abv": 5.8,
    "styleId": 17,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1037,
    "brewerId": 24,
    "name": "Hoppy Cat",
    "abv": 5.8,
    "styleId": 8,
    "serving": 0,
    "colour": 4,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "caskadian",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1038,
    "brewerId": 24,
    "name": "Etrusca",
    "abv": 9.3,
    "styleId": 30,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 5,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1039,
    "brewerId": 24,
    "name": "Caos",
    "abv": 10.9,
    "styleId": 30,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 3,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "grape ale",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1040,
    "brewerId": 24,
    "name": "Castagnale",
    "abv": 7.1,
    "styleId": 26,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1041,
    "brewerId": 24,
    "name": "Watermelon Man",
    "abv": 4.5,
    "styleId": 11,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 3,
    "bitter": 1,
    "sour": 2,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1042,
    "brewerId": 24,
    "name": "Keller for Fest",
    "abv": -1,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1043,
    "brewerId": 26,
    "name": "Bourbonic Plague",
    "abv": 12.1,
    "styleId": 3,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 3,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "bourbon,porter",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1044,
    "brewerId": 26,
    "name": "Cranberry",
    "abv": 7,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 2,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "cranberries,spices",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1045,
    "brewerId": 26,
    "name": "Diesel",
    "abv": 8.8,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 4,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": 150955,
    "untappdId": -1
  },
  {
    "id": 1046,
    "brewerId": 26,
    "name": "Elderberry",
    "abv": 8.1,
    "styleId": 3,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 1,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "elderberries,red wine",
    "ratebeerId": 142387,
    "untappdId": -1
  },
  {
    "id": 1047,
    "brewerId": 26,
    "name": "Figaro",
    "abv": 10,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 1,
    "bitter": 2,
    "sour": 5,
    "oakAged": true,
    "tags": "white figs,chardonnay",
    "ratebeerId": 144417,
    "untappdId": -1
  },
  {
    "id": 1048,
    "brewerId": 26,
    "name": "Kriek",
    "abv": 8.5,
    "styleId": 3,
    "serving": 0,
    "colour": 4,
    "body": 3,
    "sweet": 1,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "cherry,oak",
    "ratebeerId": 82022,
    "untappdId": -1
  },
  {
    "id": 1049,
    "brewerId": 26,
    "name": "Manhattan NW",
    "abv": 11.32,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 2,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "bourbon,heaven hill,cherry,apricot kernels",
    "ratebeerId": 209112,
    "untappdId": -1
  },
  {
    "id": 1050,
    "brewerId": 26,
    "name": "Shrieking Violet",
    "abv": 11,
    "styleId": 3,
    "serving": 0,
    "colour": 3,
    "body": 2,
    "sweet": 2,
    "bitter": 1,
    "sour": 3,
    "oakAged": true,
    "tags": "quad,blueberries,oak",
    "ratebeerId": 162318,
    "untappdId": -1
  },
  {
    "id": 1051,
    "brewerId": 26,
    "name": "Strawberry",
    "abv": 7.1,
    "styleId": 3,
    "serving": 0,
    "colour": 2,
    "body": 2,
    "sweet": 2,
    "bitter": 1,
    "sour": 4,
    "oakAged": true,
    "tags": "strawberries",
    "ratebeerId": 164825,
    "untappdId": -1
  },
  {
    "id": 1052,
    "brewerId": 26,
    "name": "The Vine",
    "abv": 8.85,
    "styleId": 3,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 1,
    "sour": 3,
    "oakAged": true,
    "tags": "blend,grapes,oak",
    "ratebeerId": 97626,
    "untappdId": -1
  },
  {
    "id": 1053,
    "brewerId": 26,
    "name": "Vlad the Imp Aler",
    "abv": 10.6,
    "styleId": 3,
    "serving": 0,
    "colour": 4,
    "body": 4,
    "sweet": 4,
    "bitter": 2,
    "sour": 3,
    "oakAged": true,
    "tags": "quad,wood",
    "ratebeerId": 96273,
    "untappdId": -1
  },
  {
    "id": 1054,
    "brewerId": 29,
    "name": "Hunahpu",
    "abv": 11,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 4,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1055,
    "brewerId": 29,
    "name": "Trousseau",
    "abv": -1,
    "styleId": 0,
    "serving": 0,
    "colour": 4,
    "body": 4,
    "sweet": 4,
    "bitter": 3,
    "sour": 2,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1056,
    "brewerId": 29,
    "name": "Jal Alai",
    "abv": 7.5,
    "styleId": 2,
    "serving": 0,
    "colour": 3,
    "body": 2,
    "sweet": 3,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1057,
    "brewerId": 29,
    "name": "Maduro",
    "abv": 5.5,
    "styleId": 21,
    "serving": 0,
    "colour": 4,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1058,
    "brewerId": 29,
    "name": "Kneep Deep (Continental Drift)",
    "abv": 6.8,
    "styleId": 2,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 2,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1059,
    "brewerId": 29,
    "name": "Invasion",
    "abv": 5,
    "styleId": 7,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1060,
    "brewerId": 11,
    "name": "Kellerbeer Mandarina",
    "abv": 5.3,
    "styleId": 29,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1061,
    "brewerId": 11,
    "name": "Affumicator",
    "abv": 9.6,
    "styleId": 26,
    "serving": 0,
    "colour": 2,
    "body": 4,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "smoked",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1062,
    "brewerId": 11,
    "name": "Schwarze 90",
    "abv": 11.9,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "lager",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1063,
    "brewerId": 11,
    "name": "Zwickelpils",
    "abv": 5.1,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "zwickel",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1064,
    "brewerId": 11,
    "name": "Daniela´s lager wheat",
    "abv": 5,
    "styleId": 20,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1065,
    "brewerId": 11,
    "name": "Andreator",
    "abv": 8,
    "styleId": 26,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "red",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1066,
    "brewerId": 14,
    "name": "Uri Keller",
    "abv": 9,
    "styleId": 29,
    "serving": 0,
    "colour": 4,
    "body": 4,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "dry-hopped,dunkel",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1067,
    "brewerId": 14,
    "name": "Mutiny on the bounty",
    "abv": 6,
    "styleId": 11,
    "serving": 0,
    "colour": 4,
    "body": 2,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "bounty bar",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1068,
    "brewerId": 14,
    "name": "Top of the Morning",
    "abv": 12,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "oatmeal",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1069,
    "brewerId": 14,
    "name": "Barrel Project # 6",
    "abv": 13,
    "styleId": 0,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "bourbon,barton",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1070,
    "brewerId": 14,
    "name": "Barrel Project # 8",
    "abv": 12.5,
    "styleId": 0,
    "serving": 0,
    "colour": 3,
    "body": 5,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "cognac",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1071,
    "brewerId": 14,
    "name": "Brew With Friends # 1 (w/ Magic Rock)",
    "abv": 13,
    "styleId": 14,
    "serving": 0,
    "colour": 4,
    "body": 3,
    "sweet": 2,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "cognac,calvados",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1072,
    "brewerId": 14,
    "name": "Da Hong Pao",
    "abv": 13,
    "styleId": 0,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "suchuan pepper",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1073,
    "brewerId": 14,
    "name": "Imperial Russian Vanilla Eisbock",
    "abv": 20,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 4,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "icebock,vanilla",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1074,
    "brewerId": 28,
    "name": "Black Block Bourbon Barrel Aged",
    "abv": 13,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": true,
    "tags": "bourbon",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1075,
    "brewerId": 28,
    "name": "Black Block",
    "abv": 11.2,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1076,
    "brewerId": 28,
    "name": "Súria Gluten Free",
    "abv": 5,
    "styleId": 7,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "gluten free",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1077,
    "brewerId": 28,
    "name": "Viakrucis",
    "abv": 6,
    "styleId": 2,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 1,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1078,
    "brewerId": 28,
    "name": "¡Ay, Carmela!",
    "abv": 9.2,
    "styleId": 1,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 3,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1079,
    "brewerId": 28,
    "name": "Fucking Beer Coffee Lager",
    "abv": 5,
    "styleId": 13,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "coffee,lager",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1080,
    "brewerId": 28,
    "name": "Lab Nº003 Hoppy Lager",
    "abv": 5.2,
    "styleId": 2,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "lager",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1081,
    "brewerId": 28,
    "name": "Keller 30l",
    "abv": 5.4,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1082,
    "brewerId": 28,
    "name": "Piet 30l",
    "abv": 9.9,
    "styleId": 1,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 3,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "farmhouse",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1083,
    "brewerId": 15,
    "name": "Pelašķu velns (Yarrow devil)",
    "abv": 8.8,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "yarrow",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1084,
    "brewerId": 15,
    "name": "Pūdele (Midsummer pole fire)",
    "abv": 5.9,
    "styleId": 2,
    "serving": 0,
    "colour": 3,
    "body": 2,
    "sweet": 1,
    "bitter": 5,
    "sour": 1,
    "oakAged": false,
    "tags": "smoked,pine spruce",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1085,
    "brewerId": 15,
    "name": "Akmeņrags",
    "abv": 4.5,
    "styleId": 9,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "heather,thyme",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1086,
    "brewerId": 15,
    "name": "Lenteņu kāvējs (Tapeworm slayer)",
    "abv": 7.2,
    "styleId": 8,
    "serving": 0,
    "colour": 5,
    "body": 4,
    "sweet": 2,
    "bitter": 5,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1087,
    "brewerId": 15,
    "name": "Pļava (Meadow)",
    "abv": 6.5,
    "styleId": 9,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 3,
    "oakAged": false,
    "tags": "yarrow,meadosweet,mugworm",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1088,
    "brewerId": 15,
    "name": "Kamīns (Fireplace)",
    "abv": 6.9,
    "styleId": 7,
    "serving": 0,
    "colour": 3,
    "body": 4,
    "sweet": 4,
    "bitter": 1,
    "sour": 2,
    "oakAged": false,
    "tags": "chamomile",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1089,
    "brewerId": 15,
    "name": "Rasele (Little dew)",
    "abv": 3.7,
    "styleId": 30,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 1,
    "bitter": 3,
    "sour": 2,
    "oakAged": false,
    "tags": "wormwood,catnip",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1090,
    "brewerId": 15,
    "name": "Ausma (Dawn)",
    "abv": 5.8,
    "styleId": 30,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "ginger,peppermint,mild",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1091,
    "brewerId": 15,
    "name": "Dravnieka atraitne (Beekeekeprs widow)",
    "abv": 13,
    "styleId": 25,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 4,
    "bitter": 1,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1092,
    "brewerId": 15,
    "name": "Lauķis (Redneck)",
    "abv": 5.8,
    "styleId": 29,
    "serving": 0,
    "colour": 2,
    "body": 2,
    "sweet": 3,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1093,
    "brewerId": 17,
    "name": "Barrel Aged Three Bean stout",
    "abv": 13,
    "styleId": 5,
    "serving": 0,
    "colour": 5,
    "body": 5,
    "sweet": 4,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "choco,vaniall,tonka",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1094,
    "brewerId": 17,
    "name": "Borefts kellerbier",
    "abv": 4.5,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 1,
    "sour": 2,
    "oakAged": false,
    "tags": "dry-hopped",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1095,
    "brewerId": 17,
    "name": "Cafe Sur",
    "abv": 4,
    "styleId": 22,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 1,
    "bitter": 1,
    "sour": 4,
    "oakAged": false,
    "tags": "coffee",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1096,
    "brewerId": 17,
    "name": "Farmhouse IPA",
    "abv": 6,
    "styleId": 2,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 1,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "brett",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1097,
    "brewerId": 17,
    "name": "Godshot",
    "abv": 7.5,
    "styleId": 4,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 3,
    "bitter": 3,
    "sour": 2,
    "oakAged": false,
    "tags": "coffee",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1098,
    "brewerId": 17,
    "name": "Iconoclast Quad",
    "abv": 9.5,
    "styleId": 14,
    "serving": 2,
    "colour": 4,
    "body": 3,
    "sweet": 3,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "brett",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1099,
    "brewerId": 17,
    "name": "Lawless",
    "abv": 6.5,
    "styleId": 17,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 2,
    "bitter": 2,
    "sour": 2,
    "oakAged": false,
    "tags": "farmhouse",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1100,
    "brewerId": 17,
    "name": "Norwegian Mauler",
    "abv": 7.9,
    "styleId": 4,
    "serving": 0,
    "colour": 5,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "dry stout,tea",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1101,
    "brewerId": 17,
    "name": "Oat IPA",
    "abv": 7.2,
    "styleId": 2,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 3,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "oats",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1102,
    "brewerId": 17,
    "name": "Passion Tang",
    "abv": 7,
    "styleId": 11,
    "serving": 0,
    "colour": 3,
    "body": 3,
    "sweet": 2,
    "bitter": 2,
    "sour": 4,
    "oakAged": false,
    "tags": "passionfruit,paradise",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1103,
    "brewerId": 17,
    "name": "Sverd i fjell",
    "abv": 10,
    "styleId": 1,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 3,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1104,
    "brewerId": 30,
    "name": "Passion for Mango",
    "abv": 4,
    "styleId": 22,
    "serving": 0,
    "colour": 2,
    "body": 2,
    "sweet": 1,
    "bitter": 1,
    "sour": 4,
    "oakAged": false,
    "tags": "passionfruit,mango",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1105,
    "brewerId": 30,
    "name": "Violmjöd",
    "abv": 6.9,
    "styleId": 30,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 1,
    "bitter": 1,
    "sour": 2,
    "oakAged": false,
    "tags": "violet,mead",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1106,
    "brewerId": 30,
    "name": "Drei Hopped C3",
    "abv": 4,
    "styleId": 22,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 1,
    "bitter": 1,
    "sour": 3,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1107,
    "brewerId": 30,
    "name": "Vaniljcider (cider)",
    "abv": 5.5,
    "styleId": 30,
    "serving": 0,
    "colour": 2,
    "body": 1,
    "sweet": 1,
    "bitter": 1,
    "sour": 2,
    "oakAged": false,
    "tags": "apple,vanilla",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1108,
    "brewerId": 30,
    "name": "Almost Same but More",
    "abv": 7.2,
    "styleId": 1,
    "serving": 0,
    "colour": 2,
    "body": 3,
    "sweet": 2,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1109,
    "brewerId": 30,
    "name": "Sahti",
    "abv": -1,
    "styleId": 9,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 2,
    "bitter": 1,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1110,
    "brewerId": 25,
    "name": "Lager des Houblons",
    "abv": 4.5,
    "styleId": 29,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": -1,
    "untappdId": -1
  },
  {
    "id": 1111,
    "brewerId": 25,
    "name": "Petite Princesse (w/ Jester King)",
    "abv": 2.9,
    "styleId": 28,
    "serving": 0,
    "colour": 1,
    "body": 1,
    "sweet": 1,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": 194018,
    "untappdId": -1
  },
  {
    "id": 1112,
    "brewerId": 25,
    "name": "Etoile du Nord",
    "abv": 5.5,
    "styleId": 17,
    "serving": 0,
    "colour": 1,
    "body": 2,
    "sweet": 1,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": 55445,
    "untappdId": -1
  },
  {
    "id": 1113,
    "brewerId": 25,
    "name": "Blonde d'Esquelbecq",
    "abv": 6.5,
    "styleId": 17,
    "serving": 0,
    "colour": 1,
    "body": 3,
    "sweet": 2,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "bière de garde",
    "ratebeerId": 15774,
    "untappdId": -1
  },
  {
    "id": 1114,
    "brewerId": 25,
    "name": "Rouge Flamande",
    "abv": 5.8,
    "styleId": 17,
    "serving": 0,
    "colour": 5,
    "body": 2,
    "sweet": 2,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "bière de garde",
    "ratebeerId": 12097,
    "untappdId": -1
  },
  {
    "id": 1115,
    "brewerId": 25,
    "name": "Maline",
    "abv": 5.8,
    "styleId": 11,
    "serving": 2,
    "colour": 5,
    "body": 3,
    "sweet": 3,
    "bitter": 3,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": 45746,
    "untappdId": -1
  },
  {
    "id": 1116,
    "brewerId": 25,
    "name": "Dalva",
    "abv": 8.5,
    "styleId": 1,
    "serving": 0,
    "colour": 1,
    "body": 4,
    "sweet": 4,
    "bitter": 4,
    "sour": 1,
    "oakAged": false,
    "tags": "",
    "ratebeerId": 176316,
    "untappdId": -1
  },
  {
    "id": 1117,
    "brewerId": 25,
    "name": "Winter Ale",
    "abv": 5.8,
    "styleId": 14,
    "serving": 0,
    "colour": 4,
    "body": 4,
    "sweet": 3,
    "bitter": 2,
    "sour": 1,
    "oakAged": false,
    "tags": "spices",
    "ratebeerId": -1,
    "untappdId": -1
  }
  ],
  "revision": 40
}