<?php
  include 'enablecache.php';
?>
{
    "beers": [
        {
            "id": 1,
            "name": "Alvinne Mad Tom",
            "brewerId": 8,
            "styleId": 6,
            "abv": 4,
            "oakAged": false,
            "tags": "golden ale",
            "ratebeerId": 247366,
            "untappdId": 543791,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 10,
            "name": "Alvinne Mano Negra Chili Stout",
            "brewerId": 8,
            "styleId": 5,
            "abv": 10,
            "oakAged": true,
            "tags": "chili",
            "ratebeerId": 219536,
            "untappdId": 516943,
            "serving": 2,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 11,
            "name": "Alvinne Cuvée Sofie",
            "brewerId": 8,
            "styleId": 3,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 261753,
            "untappdId": 662302,
            "serving": 2,
            "colour": 1,
            "body": 3,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 13,
            "name": "Alvinne Phi",
            "brewerId": 8,
            "styleId": 3,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 247371,
            "untappdId": 558162,
            "serving": 2,
            "colour": 1,
            "body": 4,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
       {
           "id": 1001,
           "name": "Brewdog Not Another Damned Saison",
           "brewerId": 3,
           "styleId": 17,
           "abv": 5.5,
           "oakAged": false,
           "tags": "fruit",
           "ratebeerId": -1,
           "untappdId": 1237327,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
           "id": 1002,
           "name": "Brewdog Dog D",
           "brewerId": 3,
           "styleId": 5,
           "abv": 16.1,
           "oakAged": true,
           "tags": "bourbon,vanilla,chili,naga,cacao,coffee",
           "ratebeerId": 338584,
           "untappdId": 1117053,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
           "id": 1003,
           "name": "Brewdog Hop Fiction",
           "brewerId": 3,
           "styleId": 2,
           "abv": 5.2,
           "oakAged": false,
           "tags": "fruity hops",
           "ratebeerId": 345131,
           "untappdId": 1137199,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
           "id": 1004,
           "name": "Brewdog Lizard Bride",
           "brewerId": 3,
           "styleId": 3,
           "abv": 5.7,
           "oakAged": false,
           "tags": "bitter,tart,hops,raspberries,blueberries,sour cherries",
           "ratebeerId": 353004,
           "untappdId": 1188034,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
           "id": 1005,
           "name": "Brewdog MashTag 2015",
           "brewerId": 3,
           "styleId": 0,
           "abv": 10,
           "oakAged": false,
           "tags": "Black Barley Wine,oak chips,vanilla",
           "ratebeerId": 349260,
           "untappdId": 1169811,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
        },
       {
           "id": 1006,
           "name": "Brewdog Pilot Brew 12",
           "brewerId": 3,
           "styleId": 25,
           "abv": 4.6,
           "oakAged": false,
           "tags": "orange blossom,wheat,session,honey,malts",
           "ratebeerId": 361017,
           "untappdId": 1237326,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       }, 
       {
           "id": 1007,
           "name": "BrewDog Renaissance Braggot",
           "brewerId": 3,
           "styleId": 25,
           "abv": 16.9,
           "oakAged": true,
           "tags": "imperial braggot,honey,malts",
           "ratebeerId": 329906,
           "untappdId": 1070273,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
           "id": 1008,
           "name": "Brewdog Pilot Brew 009",
           "brewerId": 3,
           "styleId": 3,
           "abv": 6.1,
           "oakAged": false,
           "tags": "spices,cherry,wild fruit",
           "ratebeerId": 330403,
           "untappdId": 1067115,
           "serving": -1,
           "colour": -1,
           "body": -1,
           "bitterness": -1,
           "sweetness": -1,
           "acidity": -1
       },
       {
            "id": 1101,
            "name": "Brewski Tropic Sneeze",
            "brewerId": 6,
            "styleId": 22,
            "abv": 3.8,
            "oakAged": false,
            "tags": "tropical fruits",
            "ratebeerId": 330477,
            "untappdId": 1049793,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1102,
            "name": "Brewski Sehe Coffee Berliner",
            "brewerId": 6,
            "styleId": 22,
            "abv": 3.8,
            "oakAged": false,
            "tags": "coffee",
            "ratebeerId": 329387,
            "untappdId": 1060920,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1103,
            "name": "Brewski MangoFeber DIPA",
            "brewerId": 6,
            "styleId": 1,
            "abv": 8,
            "oakAged": false,
            "tags": "amarillo,mosaic",
            "ratebeerId": 297901,
            "untappdId": 871771,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1104,
            "name": "Brewski PassionFeber IPA",
            "brewerId": 6,
            "styleId": 2,
            "abv": 7,
            "oakAged": false,
            "tags": "fruity hops",
            "ratebeerId": 322181,
            "untappdId": 1042477,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1105,
            "name": "Brewski From Skåne with Love",
            "brewerId": 6,
            "styleId": 17,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 353248,
            "untappdId": 1192194,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1106,
            "name": "Brewski Berliner Passion",
            "brewerId": 6,
            "styleId": 22,
            "abv": 3.8,
            "oakAged": false,
            "tags": "passion fruit",
            "ratebeerId": 329386,
            "untappdId": 1052727,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1107,
            "name": "Brewski Grape Me",
            "brewerId": 6,
            "styleId": 7,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 337031,
            "untappdId": 1104392,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1108,
            "name": "Brewski AnanasFeber APA",
            "brewerId": 6,
            "styleId": 7,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 321011,
            "untappdId": 1010091,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1109,
            "name": "Brewski Cloud City",
            "brewerId": 6,
            "styleId": 22,
            "abv": 4,
            "oakAged": false,
            "tags": "cloudberries",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1110,
            "name": "Brewski Keyline Berliner",
            "brewerId": 6,
            "styleId": 22,
            "abv": 4,
            "oakAged": false,
            "tags": "Elderflower,lime,basil",
            "ratebeerId": 361039,
            "untappdId": 1223984,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 1201,
            "name": "Kees! Pale Ale Citra Extra",
            "brewerId": 14,
            "styleId": 7,
            "abv": 4.6,
            "oakAged": false,
            "tags": "citra,hops",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1202,
            "name": "Kees! Pink Grapefruit IPA",
            "brewerId": 14,
            "styleId": 2,
            "abv": 5.5,
            "oakAged": false,
            "tags": "grapefruit,hops",
            "ratebeerId": 339886,
            "untappdId": 1149112,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1203,
            "name": "Kees! Just Another IPA",
            "brewerId": 14,
            "styleId": 2,
            "abv": 6.5,
            "oakAged": false,
            "tags": "hops,Motueka,Kahatu",
            "ratebeerId": 346154,
            "untappdId": 1197090,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1204,
            "name": "Kees! Black Oyster Saison",
            "brewerId": 14,
            "styleId": 17,
            "abv": 8,
            "oakAged": false,
            "tags": "oysters",
            "ratebeerId": 358362,
            "untappdId": 1231596,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1205,
            "name": "Kees! Indian Summer DoppelBock",
            "brewerId": 14,
            "styleId": 26,
            "abv": 9.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 357837,
            "untappdId": 1233234,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1206,
            "name": "Kees! Barrel Project #1",
            "brewerId": 14,
            "styleId": 5,
            "abv": 10.5,
            "oakAged": true,
            "tags": "Bunnahabhain,Islay,peated,whisky barrel",
            "ratebeerId": 341710,
            "untappdId": 1131414,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1207,
            "name": "Kees! Barrel Project #2",
            "brewerId": 14,
            "styleId": 5,
            "abv": 10.6,
            "oakAged": true,
            "tags": "Balmenach,Speyside,whisky barrel",
            "ratebeerId": 357831,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1208,
            "name": "Kees! Oatmeal Breakfast Stout ",
            "brewerId": 14,
            "styleId": 5,
            "abv": 10.7,
            "oakAged": false,
            "tags": "oats",
            "ratebeerId": 357829,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1209,
            "name": "Kees! American Barley wine",
            "brewerId": 14,
            "styleId": 0,
            "abv": 11.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },

{
            "id": 1210,
            "name": "Kees! Peated Imperial Stout",
            "brewerId": 14,
            "styleId": 5,
            "abv": 12,
            "oakAged": false,
            "tags": "peated whisky malts",
            "ratebeerId": 357840,
            "untappdId": 1231612,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
{
            "id": 20,
            "name": "Naparbier Insider IPA",
            "brewerId": 19,
            "styleId": 2,
            "abv": 7.2,
            "oakAged": false,
            "tags": "Sorachi Ace, Cascade",
            "ratebeerId": 351736,
            "untappdId":-1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 21,
            "name": "Naparbier Sunset IPA",
            "brewerId": 19,
            "styleId": 2,
            "abv": 4.2,
            "oakAged": false,
            "tags": "session",
            "ratebeerId": 331808,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 22,
            "name": "Naparbier / Brouwerij de Molen Iruña & Mordor",
            "brewerId": 19,
            "styleId": 11,
            "abv": 10.1,
            "oakAged": false,
            "tags": "collaboration",
            "ratebeerId": 344378 ,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 23,
            "name": "Naparbier Potemkin",
            "brewerId": 19,
            "styleId": 5,
            "abv": 12,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 339441,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 24,
            "name": "Naparbier Avant-Garde Series Barley Wine. Ed 2013",
            "brewerId": 19,
            "styleId": 0,
            "abv": 12,
            "oakAged": true,
            "tags": "wine-aged",
            "ratebeerId": 306276,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 25,
            "name": "Naparbier The Crimson Bird",
            "brewerId": 19,
            "styleId": 17,
            "abv": 6.1,
            "oakAged": false,
            "tags": "strawberry, Borefts Special",
            "ratebeerId": 359337,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
{
            "id": 31,
            "name": "Austmann Sura Bror",
            "brewerId": 1,
            "styleId": 22,
            "abv": 5,
            "oakAged": false,
            "tags": "white peaches, mint",
            "ratebeerId": 358423,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 32,
            "name": "Austmann Tre Gamle Damer",
            "brewerId": 1,
            "styleId": 10,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 218046,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 33,
            "name": "Austmann Northumberland",
            "brewerId": 1,
            "styleId": 21,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 218972,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 34,
            "name": "Austmann / Brussels Beer Project La Shaman Aztec Stout",
            "brewerId": 1,
            "styleId": 5,
            "abv": 7.8,
            "oakAged": false,
            "tags": "chipotle chili peppers, habanero peppers, cocoa beans",
            "ratebeerId": 348873,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 35,
            "name": "Austmann Fader Halvard",
            "brewerId": 1,
            "styleId": 10,
            "abv": 9,
            "oakAged": false,
            "tags": "raspberries",
            "ratebeerId": 283767,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 36,
            "name": "Austmann Utpå",
            "brewerId": 1,
            "styleId": 20,
            "abv": 4.5,
            "oakAged": false,
            "tags": "witbier, coriander, orange peel",
            "ratebeerId": 260086,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 37,
            "name": "Austmann Miss Saison",
            "brewerId": 1,
            "styleId": 17,
            "abv": 6,
            "oakAged": false,
            "tags": "ginger, lemongrass, limeleaves",
            "ratebeerId": 259504,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 38,
            "name": "Austmann Citra Saison",
            "brewerId": 1,
            "styleId": 17,
            "abv": 5.9,
            "oakAged": false,
            "tags": "citra, single hop",
            "ratebeerId": 332345,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 39,
            "name": "Austmann Norwegian Blue Norwegian",
            "brewerId": 1,
            "styleId": 17,
            "abv": 4.5,
            "oakAged": false,
            "tags": "Borefts Special, blueberries, blackcurrants",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 40,
            "name": "Austmann Smoky Seaweed Saison",
            "brewerId": 1,
            "styleId": 17,
            "abv": 5,
            "oakAged": false,
            "tags": "Borefts Special, seaweed, smoked",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 41,
            "name": "Austmann Humledugg",
            "brewerId": 1,
            "styleId": 2,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 218973,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 42,
            "name": "Austmann / Ø-Bryg Sea ESB",
            "brewerId": 1,
            "styleId": 6,
            "abv": 5,
            "oakAged": false,
            "tags": "seaweed, smoked, sea buckthorn",
            "ratebeerId": 332020,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 43,
            "name": "Austmann Mørk Skog",
            "brewerId": 1,
            "styleId": 6,
            "abv": 6,
            "oakAged": false,
            "tags": "pineshoots, bogmyrtle, wild oragano",
            "ratebeerId": 358426,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 26,
            "name": "Omnipollo Agamemnon Bourbon",
            "brewerId": 21,
            "styleId": 5,
            "abv": 13.2,
            "oakAged": false,
            "tags": "maple syrup, bourbon",
            "ratebeerId": 343478,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 27,
            "name": "Omnipollo / Prairie Omniprairie aka Abundantia Milk Choc. Caramel Stout",
            "brewerId": 21,
            "styleId": 4,
            "abv": 10,
            "oakAged": false,
            "tags": "vanilla, cocoa nibs, caramel sauce, lactose",
            "ratebeerId": 321400,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 28,
            "name": "Omnipollo Magic #4:20 Vanilla Waffle Wheat",
            "brewerId": 21,
            "styleId": 20,
            "abv": 5.2,
            "oakAged": false,
            "tags": "vanilla beans",
            "ratebeerId": 356479,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 29,
            "name": "Omnipollo / Buxton Yellow Belly Peanut Butter Biscuit Stout",
            "brewerId": 21,
            "styleId": 5,
            "abv": 11,
            "oakAged": false,
            "tags": "collaboration",
            "ratebeerId": 280975,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 30,
            "name": "Omnipollo Fatamorgana Oat/Wheat IIPA",
            "brewerId": 21,
            "styleId": 1,
            "abv": 8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 231144,
            "untappdId": -1,
            "serving": -1,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        }
    ],
    "revision": 31
}

