<?php
  include 'enablecache.php';
?>
{
    "brewers": [
        {
            "id": 0,
            "logoUrl": "demolen.jpg",
            "name": "Brouwerij De Molen",
            "shortName": "De Molen",
            "sortName": "Molen",
            "city": "Bodegraven",
            "country": "The Netherlands",
            "description": "",
            "website": "http://www.brouwerijdemolen.nl",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 8,
            "logoUrl": "alvinne.jpg",
            "name": "Brouwerij Alvinne",
            "shortName": "Alvinne",
            "sortName": "Alvinne",
            "city": "Moen",
            "country": "Belgium",
            "description": "",
            "website": "http://www.alvinne.be",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 9,
            "logoUrl": "narke.png",
            "name": "Närke Kulturbryggeri",
            "shortName": "Närke",
            "sortName": "Narke",
            "city": "Örebro",
            "country": "Sweden",
            "description": "",
            "website": "http://www.kulturbryggeri.se",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 11,
            "logoUrl": "ganstaller.jpg",
            "name": "Gänstaller Bräu",
            "shortName": "Gänstaller",
            "sortName": "Ganstaller",
            "city": "Hallerndorf",
            "country": "Germany",
            "description": "",
            "website": "http://www.gaenstaller.de",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 14,
            "logoUrl": "kees.png",
            "name": "Brouwerij Kees!",
            "shortName": "Kees!",
            "sortName": "Kees",
            "city": "Middelburg",
            "country": "The Netherlands",
            "description": "",
            "website": "http://www.brouwerijkees.nl",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 15,
            "logoUrl": "labietis.png",
            "name": "Alus Darbnīca Labietis",
            "shortName": "Labietis",
            "sortName": "Labietis",
            "city": "Riga",
            "country": "Latvia",
            "description": "",
            "website": "http://www.labietis.lv",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 17,
            "logoUrl": "lervig.jpg",
            "name": "Lervig Aktiebryggeri",
            "shortName": "Lervig",
            "sortName": "Lervig",
            "city": "Stavanger",
            "country": "Norway",
            "description": "",
            "website": "http://www.lervig.no",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 20,
            "logoUrl": "oedipus.jpg",
            "name": "Oedipus",
            "shortName": "Oedipus",
            "sortName": "Oedipus",
            "city": "Amsterdam",
            "country": "The Netherlands",
            "description": "",
            "website": "http://www.oedipusbrewing.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 21,
            "logoUrl": "omnipollo.png",
            "name": "Omnipollo",
            "shortName": "Omnipollo",
            "sortName": "Omnipollo",
            "city": "Stockholm",
            "country": "Sweden",
            "description": "",
            "website": "http://www.omnipollo.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 22,
            "logoUrl": "bakunin.jpg",
            "name": "Bakunin Brewery",
            "shortName": "Bakunin",
            "sortName": "Bakunin",
            "city": "Saint-Petersburg",
            "country": "Russia",
            "description": "",
            "website": "http://www.bakuninbrewery.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 23,
            "logoUrl": "bevog.jpg",
            "name": "Bevog Brewery",
            "shortName": "Bevog",
            "sortName": "Bevog",
            "city": "Bad Radkersburg",
            "country": "Austria",
            "description": "",
            "website": "http://www.bevog.at",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 24,
            "logoUrl": "birradelborgo.jpg",
            "name": "Birra del Borgo",
            "shortName": "Birra del Borgo",
            "sortName": "Birra del Borgo",
            "city": "Borgorose",
            "country": "Italy",
            "description": "",
            "website": "http://www.birradelborgo.it",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 25,
            "logoUrl": "thiriez.jpg",
            "name": "Brasserie Thiriez",
            "shortName": "Thiriez",
            "sortName": "Thiriez",
            "city": "Esquelbecq",
            "country": "France",
            "description": "",
            "website": "http://www.brasseriethiriez.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 26,
            "logoUrl": "cascade.png",
            "name": "Cascade Brewing",
            "shortName": "Cascade",
            "sortName": "Cascade",
            "city": "Portland",
            "country": "USA",
            "description": "",
            "website": "http://www.cascadebrewingbarrelhouse.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 27,
            "logoUrl": "drybitter.jpg",
            "name": "Dry & Bitter Brewing Company",
            "shortName": "Dry & Bitter",
            "sortName": "Dry Bitter",
            "city": "Frederiksborg",
            "country": "Denmark",
            "description": "",
            "website": "https://www.facebook.com/Dry-Bitter-Brewing-Company-1519454774996343/",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 28,
            "logoUrl": "lapirata.jpg",
            "name": "Cerveses La Pirata",
            "shortName": "La Pirata",
            "sortName": "Pirata",
            "city": "Suria",
            "country": "Spain",
            "description": "",
            "website": "http://www.cervesalapirata.com",
            "latitude": 52.084347,
            "longitude": 4.739305
        },
        {
            "id": 29,
            "logoUrl": "cigarcity.jpg",
            "name": "Cigar City Brewing",
            "shortName": "Cigar City",
            "sortName": "Cigar City",
            "city": "Tampa",
            "country": "USA",
            "description": "",
            "website": "https://cigarcitybrewing.com",
            "latitude": 52.084329,
            "longitude": 4.739447,
            "hide": true
        },
        {
            "id": 30,
            "logoUrl": "sahtipaja.jpg",
            "name": "Sahtipaja",
            "shortName": "Sahtipaja",
            "sortName": "Sahtipaja",
            "city": "Sätila",
            "country": "Sweden",
            "description": "",
            "website": "https://www.facebook.com/sahtipaja",
            "latitude": 52.084329,
            "longitude": 4.739447,
            "hide": true
        },
        {
            "id": 31,
            "logoUrl": "brewdog.png",
            "name": "BrewDog",
            "shortName": "BrewDog",
            "sortName": "Brewdog",
            "city": "Ellon",
            "country": "Scotland",
            "description": "",
            "website": "https://www.brewdog.com",
            "latitude": 52.084329,
            "longitude": 4.739447,
            "hide": true
        }
    ],
    "revision": 31
}
